urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Uncomment the next line to enable the admin:
    (r'^$', 'nirvana.pkg.views.welcome'),
    (r'^admin/', include(admin.site.urls)),
    (r'^token/', 'nirvana.pkg.views.api_token'),
    (r'^categories/$', 'nirvana.pkg.views.categories'),
    (r'^category/new/$', 'nirvana.pkg.views.category_new'),
    (r'^category/(?P<slug>[-\w]+)/$', 'nirvana.pkg.views.category'),
    (r'^package/new/$', 'nirvana.pkg.views.package_new'),
    (r'^package/(?P<slug>[-\w]+)/latest/new/$', 'nirvana.pkg.views.variant_new', {'version_slug': None}),
    (r'^package/(?P<slug>[-\w]+)/(?P<version_slug>[-\w.]+)/new/$', 'nirvana.pkg.views.variant_new'), # TODO: fix the version regex

    (r'^package/(?P<slug>[-\w]+)/latest/(?P<variant_slug>[-\w]+)/edit/$', 'nirvana.pkg.views.variant_edit', {'version_slug': None}),
    (r'^package/(?P<slug>[-\w]+)/(?P<version_slug>[-\w.]+)/(?P<variant_slug>[-\w.]+)/edit/$', 'nirvana.pkg.views.variant_edit'), # TODO: fix the version regex

    (r'^package/(?P<slug>[-\w]+)/new/$', 'nirvana.pkg.views.version_new'),
    (r'^package/(?P<slug>[-\w]+)/edit/$', 'nirvana.pkg.views.package_edit'),
    (r'^package/(?P<slug>[-\w]+)/managers/$', 'nirvana.pkg.views.package_edit_managers'),

    (r'^package/(?P<slug>[-\w]+)/latest/edit/$', 'nirvana.pkg.views.version_edit', {'version_slug': None}),
    (r'^package/(?P<slug>[-\w]+)/(?P<version_slug>[-\w.]+)/edit/$', 'nirvana.pkg.views.version_edit'), # TODO: fix the version regex

    (r'^packages/(?P<slug>[-\w]+)/$', 'nirvana.pkg.views.package'),

    (r'^packages/(?P<slug>[-\w]+)/latest/$', 'nirvana.pkg.views.version', {'version_slug': None}),
    (r'^packages/(?P<slug>[-\w]+)/(?P<version_slug>[-\w.]+)/$', 'nirvana.pkg.views.version'), # TODO: fix the version regex

    (r'^packages/(?P<slug>[-\w]+)/latest/(?P<variant_slug>[-\w]+)/$', 'nirvana.pkg.views.variant', {'version_slug': None}),
    (r'^packages/(?P<slug>[-\w]+)/(?P<version_slug>[-\w.]+)/(?P<variant_slug>[-\w.]+)/$', 'nirvana.pkg.views.variant'), # TODO: fix the version regex

    (r'^packages/(?P<slug>[-\w]+)/latest/(?P<variant_slug>[-\w]+)/(?P<usefile>[-\w.]+)\.use$', 'nirvana.pkg.views.usefile', {'version_slug': None}),
    (r'^packages/(?P<slug>[-\w]+)/(?P<version_slug>[-\w.]+)/(?P<variant_slug>[-\w.]+)/(?P<usefile>[-\w.]+)\.use$', 'nirvana.pkg.views.usefile'), # TODO: fix the version regex
    (r'^packages/(?P<slug>[-\w]+)/latest/(?P<variant_slug>[-\w]+)/(?P<checksums>[-\w.]+)\.checksums$', 'nirvana.pkg.views.checksums', {'version_slug': None}),
    (r'^packages/(?P<slug>[-\w]+)/(?P<version_slug>[-\w.]+)/(?P<variant_slug>[-\w.]+)/(?P<checksums>[-\w.]+)\.checksums$', 'nirvana.pkg.views.checksums'), # TODO: fix the version regex
    (r'^packages/(?P<slug>[-\w]+)/latest/(?P<variant_slug>[-\w]+)/(?P<checksums_signature>[-\w.]+)\.checksums\.sig$', 'nirvana.pkg.views.checksums_signature', {'version_slug': None}),
    (r'^packages/(?P<slug>[-\w]+)/(?P<version_slug>[-\w.]+)/(?P<variant_slug>[-\w.]+)/(?P<checksums_signature>[-\w.]+)\.checksums\.sig$', 'nirvana.pkg.views.checksums_signature'), # TODO: fix the version regex



    (r'^accounts/', include('registration.urls')),

    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/home/fred/dev/ooc/nirvana/media'}), # TODO: only for development

    # api
    (r'^api/authorized/$', 'nirvana.pkg.views.api_authorized'),
    (r'^api/submit/$', 'nirvana.pkg.views.api_submit'),
    (r'^api/categories/$', 'nirvana.pkg.views.api_categories'),
    (r'^api/search/$', 'nirvana.pkg.views.api_search'),
    (r'^api/category/(?P<slug>[-\w]+)/$', 'nirvana.pkg.views.api_category'),
    (r'^api/packages/(?P<slug>[-\w]+)/$', 'nirvana.pkg.views.api_package'),
    (r'^api/packages/(?P<slug>[-\w]+)/latest/$', 'nirvana.pkg.views.api_version', {'version_slug': None}),
    (r'^api/packages/(?P<slug>[-\w]+)/(?P<version_slug>[-\w.]+)/$', 'nirvana.pkg.views.api_version'),
    (r'^api/packages/(?P<slug>[-\w]+)/latest/(?P<variant_slug>[-\w.]+)/$', 'nirvana.pkg.views.api_variant', {'version_slug': None}),
    (r'^api/packages/(?P<slug>[-\w]+)/(?P<version_slug>[-\w.]+)/(?P<variant_slug>[-\w.]+)/$', 'nirvana.pkg.views.api_variant'),
)

pkg/models.py
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User

from nirvana.pkg.stuff import DBVersionSlugField, sign

class Package(models.Model):
    slug = models.SlugField(primary_key=True, max_length=50)
    name = models.CharField(max_length=128)
    author = models.ForeignKey(User)
    homepage = models.URLField(null=True, blank=True)
    category = models.ForeignKey('Category')

    @property
    def latest_version(self):
        objects = Version.objects.filter(package=self, latest=True)
        if objects:
            return objects[0]
        else:
            return None

    def __unicode__(self):
        return self.name

    def get_authorized_variants(self, user):
        variants = []
        if user.is_authenticated():
            versions = Version.objects.filter(package=self)
            if user == self.author:
                return [v.slug for v in Variant.objects.filter(version__in=versions)]
            for permission in self.manager_permissions.filter(user=user):
                if Variant.objects.filter(slug=permission.variant_slug, version__in=versions):
                    variants.append(permission.variant_slug)
        return variants

    def is_authorized_for_variant(self, user, variant_slug, skip_authentication=False):
        if (user.is_authenticated() or skip_authentication):
            if user == self.author:
                return True
            for permission in self.manager_permissions.all():
                if (permission.user == user and permission.variant_slug == variant_slug):
                    return True
        return False

    @classmethod
    def search(cls, text):
        q = None
        for field in ('name', 'slug', 'author__username'):
            kwargs = {'%s__icontains' % field: text}
            current = Q(**kwargs)
            if q is None:
                q = current
            else:
                q = q | current
        return cls.objects.filter(q)

class ManagerPermission(models.Model):
    user = models.ForeignKey(User)
    variant_slug = models.SlugField(max_length=50)
    package = models.ForeignKey(Package, related_name='manager_permissions')

    def __unicode__(self):
        return '%s -> %s' % (self.user, self.variant_slug)

class Version(models.Model):
    slug = DBVersionSlugField(max_length=50)
    name = models.CharField('Name', max_length=128, blank=True)
    package = models.ForeignKey('Package')
    latest = models.BooleanField('Latest version')

    def __unicode__(self):
        return '%s %s' % (self.slug, self.name)

    def make_latest(self):
        """
            mark this version as the latest available version.
            This will not save self.
        """
        for version in Version.objects.filter(package=self.package):
            if (version.latest and version != self):
                version.latest = False
                version.save()
        self.latest = True

class Variant(models.Model):
    slug = models.SlugField(max_length=50)
    name = models.CharField('Name', max_length=128, blank=True)
    version = models.ForeignKey(Version)
    usefile = models.TextField()
    checksums = models.TextField(blank=True)
    checksums_signature = models.TextField(blank=True)

    def __unicode__(self):
        return '%s %s' % (self.slug, self.name)

    def set_signature(self):
        if self.checksums:
            if not self.checksums.endswith('\n'):
                self.checksums += '\n'
            self.checksums_signature = sign(self.checksums.encode('utf-8'))
        else:
            self.checksums_signature = ''

class Category(models.Model):
    slug = models.SlugField(primary_key=True, max_length=50)
    name = models.CharField(max_length=128)

    def __unicode__(self):
        return self.name

pkg/forms.py
from django.forms import ModelForm, BooleanField, ChoiceField, ValidationError
from django.forms.models import modelformset_factory
from nirvana.pkg.models import Package, Version, Category, Variant, ManagerPermission

class NewPackageForm(ModelForm):
    class Meta:
        model = Package
        fields = ('slug', 'name', 'homepage', 'category')

class EditPackageForm(ModelForm):
    class Meta:
        model = Package
        fields = ('name', 'homepage', 'category') # Sorry man, can't change the slug.

class NewCategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ('slug', 'name')

class NewVersionForm(ModelForm):
    class Meta:
        model = Version
        fields = ('slug', 'name', 'latest')

EditVersionForm = NewVersionForm

class NewVariantForm(ModelForm):
    class Meta:
        model = Variant
        fields = ('slug', 'name', 'usefile', 'checksums')

    def clean_slug(self):
        if not self.package.is_authorized_for_variant(self.request.user, self.cleaned_data['slug']):
            raise ValidationError('You are not authorized to edit / create this variant.')
        return self.cleaned_data['slug']

EditVariantForm = NewVariantForm

ManagerPermissionFormSet = modelformset_factory(ManagerPermission, exclude=('package',), can_delete=True)

templates/pkg/api_token.html
{% extends "base.html" %}
{% block content %}
<h2>API token</h2>
<p>Your api token is: <b>{{ api_token }}</b></p>
<p>Changing your password changes your api token.</p>
{% endblock %}

templates/pkg/categories.html
{% extends "base.html" %}
{% block content %}
    <ul>
    {% for category in categories %}
        <li><a href="{% url nirvana.pkg.views.category slug=category.slug %}">{{ category.name }}</a></li>
    {% empty %}
    {% if not user.is_authenticated %}
    No categories.
    {% endif %}
    {% endfor %}
    </ul>
{% endblock %}

templates/pkg/category.html
{% extends "base.html" %}
{% block content %}
    <h2>{{ category_name }}</h2>
    <ul>
    {% for package in packages %}
        <li><a href="{% url nirvana.pkg.views.package slug=package.slug %}">{{ package.name }}</a></li>
    {% endfor %}
    </ul>
{% endblock %}

templates/pkg/package.html
{% extends "base.html" %}
{% block content %}
    <h2>{{ package.name }}</h2>
    {% if user.is_authenticated %}
    {% ifequal user package.author %}
    <a href="{% url nirvana.pkg.views.package_edit slug=package.slug %}">edit</a> - <a href="{% url nirvana.pkg.views.package_edit_managers slug=package.slug %}">managers</a> - <a href="{% url nirvana.pkg.views.version_new slug=package.slug %}">upload new version</a>
    {% endifequal %}
    {% endif %}
    <ul>
    {% for version in versions %}
        {% if version.latest %}
            <b>
        {% endif %}
            <li><a href="{% url nirvana.pkg.views.version slug=package.slug version_slug=version.slug %}">{{ version.slug }} {{ package.latest_version.name }}</a>{% if user.is_authenticated %}{% ifequal user package.author %}<a href="{% url nirvana.pkg.views.version_edit slug=package.slug version_slug=version.slug %}">- edit</a>{% endifequal %}{% endif %}</li>
        {% if version.latest %}
            </b>
        {% endif %}
    {% empty %}
    No versions.
    {% endfor %}
    </ul>
{% endblock %}

templates/pkg/package_edit.html
{% extends "base.html" %}

{% block content %}

<form method="post" action="">{% csrf_token %}
    <div class="fieldWrapper">
        {{ form.name.errors }}
        <label for="id_name">Name:</label>
        {{ form.name }}
    </div>
    <div class="fieldWrapper">
        {{ form.homepage.errors }}
        <label for="id_homepage">Homepage:</label>
        {{ form.homepage }}
    </div>
    <div class="fieldWrapper">
        {{ form.category.errors }}
        <label for="id_category">Category:</label>
        {{ form.category }}
    </div>
    <div class="fieldWrapper">
        {{ form.latest_version.errors }}
        <label for="id_latest_version">Latest Version:</label>
        {{ form.latest_version }}
    </div>
    <input type="submit" value="edit" />
</form>

{% endblock %}

templates/pkg/package_edit_managers.html
{% extends "base.html" %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    <table>
    {{ formset }}
    </table>
    <input type="submit" value="edit" /></form>
{% endblock %}

templates/pkg/package_new.html
{% extends "base.html" %}

{% block content %}

<form method="post" action="">{% csrf_token %}
    <div class="fieldWrapper">
        {{ form.slug.errors }}
        <label for="id_slug">Slug:</label>
        {{ form.slug }}
        <p>The package slug is a short identifier that is used for url construction.<br/>
        That is <strong>required</strong> to be the name of the usefile.<br/>
        Example: <em>gtk</em> where the usefile is named <em>gtk.use</em></p>
    </div>
    <div class="fieldWrapper">
        {{ form.name.errors }}
        <label for="id_name">Name:</label>
        {{ form.name }}
        <p>The package name is the longer, human-readable name of the package.<br/>
        Example: <em>ooc-gtk</em></p>
    </div>
    <div class="fieldWrapper">
        {{ form.homepage.errors }}
        <label for="id_homepage">Homepage:</label>
        {{ form.homepage }}
        <p>The homepage of your package. If you have none, just leave it out.</p>
    </div>
    <div class="fieldWrapper">
        {{ form.category.errors }}
        <label for="id_category">Category:</label>
        {{ form.category }}
        <p>The category of your package - if no category matches, <a href="/category/new">create one</a>.</p>
    </div>
    <input type="submit" value="new" />
</form>

{% endblock %}

templates/pkg/variant.html
{% extends "base.html" %}
{% block content %}
<p><a href="{% url nirvana.pkg.views.usefile slug=package.slug version_slug=version.slug variant_slug=variant.slug usefile=package.slug %}">get usefile</a><br/>
<a href="{% url nirvana.pkg.views.checksums slug=package.slug version_slug=version.slug variant_slug=variant.slug checksums=package.slug %}">get checksums</a><br/>
<a href="{% url nirvana.pkg.views.checksums_signature slug=package.slug version_slug=version.slug variant_slug=variant.slug checksums_signature=package.slug %}">get checksums signature</a></p>
{{ block.super }}
{% endblock %}

templates/pkg/variant_edit.html
{% extends "base.html" %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    <div class="fieldWrapper">
        {{ form.slug.errors }}
        <label for="id_slug">Slug:</label>
        {{ form.slug }}
    </div>
    <div class="fieldWrapper">
        {{ form.name.errors }}
        <label for="id_name">Name (optional):</label>
        {{ form.name }}
    </div>
    <div class="fieldWrapper">
        {{ form.usefile.errors }}
        <label for="id_usefile">Usefile:</label>
        {{ form.usefile }}
    </div>
    <div class="fieldWrapper">
        {{ form.checksums.errors }}
        <label for="id_checksum">Checksums:</label>
        {{ form.checksums }}
    </div>
    <input type="submit" value="edit" /></form>
{% endblock %}

templates/pkg/variant_new.html
{% extends "base.html" %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    <div class="fieldWrapper">
        {{ form.slug.errors }}
        <label for="id_slug">Slug:</label>
        {{ form.slug }}
    </div>
    <div class="fieldWrapper">
        {{ form.name.errors }}
        <label for="id_name">Name (optional):</label>
        {{ form.name }}
    </div>
    <div class="fieldWrapper">
        {{ form.usefile.errors }}
        <label for="id_usefile">Usefile:</label>
        {{ form.usefile }}
    </div>
    <div class="fieldWrapper">
        {{ form.checksums.errors }}
        <label for="id_checksum">Checksums:</label>
        {{ form.checksums }}
    </div>
    <input type="submit" value="new" /></form>
{% endblock %}

templates/pkg/version.html
{% extends "pkg/package.html" %}
{% block content %}
<p>You have selected {{ package.name }} {{ version }}. Available variants:</p>

<ul>
    {% for variant_slug, action in variants.items %}
        <li>
            <a href="{% url nirvana.pkg.views.variant slug=package.slug version_slug=version.slug variant_slug=variant_slug %}">{{ variant_slug }}</a>
{% ifequal action "edit" %}
- <a href="{% url nirvana.pkg.views.variant_edit slug=package.slug version_slug=version.slug variant_slug=variant_slug %}">edit</a>
{% endifequal %}
        </li>
    {% empty %}
    None.
    {% endfor %}
</ul>
{% if user.is_authenticated %}
<p><a href="{% url nirvana.pkg.views.variant_new slug=package.slug version_slug=version.slug %}">create new variant</a></p>
{% endif %}
{{ block.super }}
{% endblock %}

templates/pkg/version_edit.html
{% extends "base.html" %}

{% block content %}

<form method="post" action="">{% csrf_token %}
    <div class="fieldWrapper">
        {{ form.slug.errors }}
        <label for="id_slug">Slug:</label>
        {{ form.slug }}
    </div>
    <div class="fieldWrapper">
        {{ form.name.errors }}
        <label for="id_name">Name (optional):</label>
        {{ form.name }}
    </div>
    <div class="fieldWrapper">
        {{ form.latest.errors }}
        <label for="id_latest">Latest version:</label>
        {{ form.latest }}
    </div>
    <input type="submit" value="edit" />
</form>

{% endblock %}

templates/pkg/version_new.html
{% extends "base.html" %}

{% block content %}

<form method="post" action="">{% csrf_token %}
    <div class="fieldWrapper">
        {{ form.slug.errors }}
        <label for="id_slug">Slug:</label>
        {{ form.slug }}
        <p>The version slug is the short, mostly numeric identifier of the version; it also will be used
        for url construction.<br/>
        Example: <em>0.1</em><br/>
        The special version slug <em>head</em> is for usefiles that describe the bleeding-edge
        development version.</p>    
    </div>
    <div class="fieldWrapper">
        {{ form.name.errors }}
        <label for="id_name">Name (optional):</label>
        {{ form.name }}
        <p>The version name is the codename of the version, if any. You can also leave it out.</br>
        Example: <em>Hardy Heron</em></p>
    </div>
    <div class="fieldWrapper">
        {{ form.latest.errors }}
        <label for="id_latest">Latest version:</label>
        {{ form.latest }}
        <p>Activate if you want to have this as the latest (= default) version.</p>
    </div>
    <input type="submit" value="new" />
</form>

{% endblock %}

templates/pkg/welcome.html
{% extends "base.html" %}
{% block content %}
<h2>Welcome!</h2>
<p>At the ooc nirvana, you can browse package usefiles and even upload your own.</p>
<p>If you want to download packages from nirvana, make sure you have added the gpg
public key first:</p>
<blockquote>
curl http://nirvana.ooc-lang.org/nirvana.asc > nirvana.asc<br/>
reincarnate add-key nirvana.asc
</blockquote>
<p>
Please make sure this key is the same as <a href="http://github.com/fredreichbier/nirvana/blob/master/nirvana.asc">here</a>. If it is not, please tell us at #ooc-lang on freenode.
</p>
{% endblock %}